### ISSUE TITLE
Uncaught Invariant Violation: addComponentAsRefTo

### ISSUE THREAD

**Issue by leefsmp** [AdaptiveConsulting/react-flex-layout#16]
I'm getting the following error in the console when trying the simple example from the readme:

```
invariant.js:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

Is there an easy way to fix it? Running React 15.3.2, is it a version conflict?

Thanks

**Comment by nickytonline** [comment]
@leefsmp, 

Try this first. Clean your `node_modules` and reinstall. Does that change anything for you?

If not,  take a peek at this gist to see if it helps with your issue, https://gist.github.com/jimfb/4faa6cbfb1ef476bd105

If you're still stuck, would you be able to provide a repo where the issue can be replicated?

**Comment by leefsmp** [comment]
Thanks for quick feedback. Tried a clean/npm install by error is still there :'(   It can't be a ref problem, my components are being loaded in just in render's ... doing an "npm ls" shows I have different version of react in my project and in flex-layout, but how do I get rid of this?

  leefsmp$ npm ls | grep react
    ├─┬ babel-preset-react@6.16.0
    │ ├── babel-plugin-transform-react-display-name@6.8.0
    │ ├─┬ babel-plugin-transform-react-jsx@6.8.0
    │ │ └── babel-helper-builder-react-jsx@6.9.0
    │ ├── babel-plugin-transform-react-jsx-self@6.11.0
    │ └── babel-plugin-transform-react-jsx-source@6.9.0
    │ └─┬ react-element-to-jsx-string@3.2.0
    ├─┬ eslint-config-standard-react@4.2.0
    ├─┬ eslint-plugin-react@6.4.1
    ├── griddle-react@0.6.1
    ├─┬ react@15.3.2
    ├── react-addons-test-utils@15.3.2
    ├─┬ react-bootstrap@0.30.5
    │ ├── react-overlays@0.6.10
    │ ├── react-prop-types@0.4.0
    ├── react-contenteditable@2.0.1
    ├─┬ react-dimensions@1.3.0
    ├── react-dom@15.3.2
    ├─┬ react-flex-layout@0.9.5
    │ ├─┬ react@0.14.8
    │ └── react-dom@0.14.8
    ├─┬ react-grid-layout@0.13.9
    │ ├── react-draggable@2.2.2
    │ └── react-resizable@1.4.5
    ├─┬ react-modal@1.5.2
    ├── react-prefixer@1.1.4
    ├─┬ react-redux@4.4.5
    │ └── hoist-non-react-statics@1.2.0
    ├─┬ react-router@2.8.1
    ├─┬ react-select@1.0.0-rc.2
    │ └── react-input-autosize@1.1.0
    ├─┬ react-split-pane@0.1.51
    │ └── react-style-proptype@1.2.0
    ├─┬ redbox-react@1.3.2

**Comment by kjetilge** [comment]
I have the same problem with a minimal test-project with only this code:
```
import React, { Component } from 'react';
import './App.css';
var Layout = require('react-flex-layout').Layout


class App extends Component {
  render() {
    return (
      <Layout fill='window'>
        <Layout layoutWidth='flex'>Column1</Layout>
        <Layout layoutWidth={100}>Column2</Layout>
      </Layout>
    );
  }
}
export default App;
```

Repo is [here](git@github.com:kjetilge/flex-layout-with-error.git)

**Comment by nickytonline** [comment]
@kjetilge @leefsmp, I can definitely confirm the issue is related to two versions of react being present. The issue is that we're not using `peerDependencies` for react in our package.json. I've got a PR coming up for this.

**Comment by nickytonline** [comment]
if you want to test my fix, simply replace your reference to '`react-flex-layout` in your package.json with this, `"react-flex-layout": "https://github.com/nickytonline/react-flex-layout.git"`

**Comment by nickytonline** [comment]
@raybooysen can you review my PR this when you have a chance? One thing I discovered is `npm link` and peerDependencies don't play nice together which is why I had to test it via `"react-flex-layout": "https://github.com/nickytonline/react-flex-layout.git"`. To test you can use @kjetilge's repo, https://github.com/kjetilge/flex-layout-with-error

**Comment by raybooysen** [comment]
Looks good to me!

**Comment by kjetilge** [comment]
Yess! It works for me too \_(ツ)_/. When testing the first time I got a blank page, then I wrapped the Layout component in a div, then it worked. Perhaps this should be show in the usage section. My working code:
```
<div>
  <h1>Simple test</h1>
  <Layout>
    <Layout layoutWidth={100}>Column1</Layout>
    <LayoutSplitter />
    <Layout layoutWidth='flex'>Column2</Layout>
  </Layout>
</div>
```

**Comment by nickytonline** [comment]
@kjetilge awesome. I'm just getting access to publish the updated version to npm. Version 0.9.6 should be available in the next day or so. Thanks for your patience.

**Comment by nickytonline** [comment]
@kjetilge 0.9.6 has been published, https://www.npmjs.com/package/react-flex-layout
